# Mutual Fund Analytics Dashboard

## Notebook 4 : Feature Engineering

### Objective

Create new business features from the cleaned mutual fund dataset to support SQL analysis and Power BI dashboard.

### Business Goal

Generate useful metrics such as year, month, daily return, rolling average, and volatility to improve fund performance analysis.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data_cleaned/cleaned_mutual_funds_data.csv")

In [3]:
df["date"] = pd.to_datetime(df["date"])

In [4]:
df["Year"] = df["date"].dt.year

In [5]:
df["Year"] = df["date"].dt.year

In [6]:
df[["date","Year"]].head()

        date  Year
0 2008-05-29  2008
1 2008-05-29  2008
2 2008-05-29  2008
3 2008-05-29  2008
4 2008-05-29  2008

In [7]:
df["Month"] = df["date"].dt.month_name()

In [8]:
df[["date","Month"]].head()

        date Month
0 2008-05-29   May
1 2008-05-29   May
2 2008-05-29   May
3 2008-05-29   May
4 2008-05-29   May

In [9]:
df["Quarter"] = df["date"].dt.quarter

In [10]:
df["Day"] = df["date"].dt.day

In [11]:
df["Day_Name"] = df["date"].dt.day_name()

In [12]:
df = df.sort_values(["scheme_name","date"])

In [13]:
df["Daily_Return"] = (
    df.groupby("scheme_name")["net_asset_value"]
      .pct_change()
)

In [14]:
df[["scheme_name",
    "date",
    "net_asset_value",
    "Daily_Return"]].head(15)

,scheme_name,date,net_asset_value,Daily_Return
10535,(IDFC FMP - MS - 30 - DIVIDEND,2011-04-25,10.0000,NaN
9424,1.\tBenchmark Short Term Fund - Growth Option,2011-08-17,10.5980,NaN
9425,2.\tBenchmark Short Term Fund - Dividend Reinv...,2011-08-17,10.0000,NaN
9426,3.\tBenchmark Short Term Fund - Dividend Reinv...,2011-08-17,10.0086,NaN
35512,360 ONE Balanced Hybrid Fund - Direct Plan - IDCW,2023-10-27,9.9382,NaN
35514,360 ONE Balanced Hybrid Fund - Regular Plan - ...,2023-10-27,9.9251,NaN
35515,360 ONE Balanced Hybrid Fund- Direct Plan - Gr...,2023-10-27,9.9382,NaN
35513,360 ONE Balanced Hyrbrid fund - Regular Plan -...,2023-10-27,9.9251,NaN
16867,360 ONE Dynamic Bond Fund - Regular Plan - Gro...,2023-10-27,19.2438,NaN
16943,360 ONE Dynamic Bond Fund Direct Plan Growth,2023-10-27,20.2173,NaN
16947,360 ONE Dynamic Bond Fund Direct Plan Monthly ...,2023-10-27,12.7557,NaN
16944,360 ONE Dynamic Bond Fund Direct Plan Quarterl...,2023-10-27,18.6596,NaN
16941,360 ONE Dynamic Bond Fund Regular Plan Bonus,2023-10-27,19.2437,NaN
16946,360 ONE Dynamic Bond Fund Regular Plan Half Ye...,2023-10-27,18.5701,NaN
16945,360 ONE Dynamic Bond Fund Regular Plan Monthly...,2023-10-27,11.9465,NaN

In [15]:
df["Rolling_NAV"] = (
    df.groupby("scheme_name")["net_asset_value"]
      .transform(lambda x: x.rolling(7).mean())
)

In [16]:
df["Volatility"] = (
    df.groupby("scheme_name")["Daily_Return"]
      .transform(lambda x: x.rolling(30).std())
)

In [17]:
df.to_csv(
    "../data_cleaned/mutual_fund_featured.csv",
    index=False
)

print("Feature engineered dataset saved successfully.")

Feature engineered dataset saved successfully.

In [18]:
scheme_counts = (
    df.groupby("scheme_name")["date"]
      .nunique()
      .sort_values(ascending=False)
)

scheme_counts.head(10)

scheme_name
Edelweiss Liquid Fund - Retail Plan - Weekly Dividend Option                       2
Edelweiss Liquid Fund - Retail Plan - Growth Option                                2
GFRF (Dividend - Weekly)                                                           2
CPSE ETF                                                                           2
quant Tax Plan - IDCW Option - Direct Plan                                         1
3.\tBenchmark Short Term Fund - Dividend Reinvestment Option - Weekly Frequency    1
����ABN AMRO Fixed Term Plan - Series 5: Quarterly Plan A-Growth Option            1
360 ONE ELSS Nifty 50 Tax Saver Index Fund - Regular Plan - Growth                 1
360 ONE Balanced Hybrid Fund - Direct Plan - IDCW                                  1
360 ONE Balanced Hybrid Fund - Regular Plan - Growth                               1
Name: date, dtype: int64

In [19]:
scheme_counts.describe()

count    35555.000000
mean         1.000113
std          0.010606
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          2.000000
Name: date, dtype: float64